version: '3'

services:
  web:
    build: ../..
    container_name: de-cguard_frontend
    networks:
      - docker
    labels:
      - traefik.enable=true
      - traefik.http.routers.web-decguardfrontend.entrypoints=websecure
      - traefik.http.routers.web-decguardfrontend.rule=Host(`cguard.de`, `www.cguard.de`)
      - traefik.http.routers.web-decguardfrontend.tls.certresolver=le
      - traefik.http.services.web-decguardfrontend.loadbalancer.server.port=80
    restart: always

networks:
  default:
  docker:
    external:
      name: docker
